//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WB_CFDI_V1.WS_CFDI {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ValidadorPortBinding", Namespace="http://validar/")]
    public partial class Validador : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidaAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaAgenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaAllEOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaAgenteEOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Validador() {
            this.Url = global::WB_CFDI_V1.Properties.Settings.Default.WB_CFDI_V1_WS_CFDI_Validador;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidaAllCompletedEventHandler ValidaAllCompleted;
        
        /// <remarks/>
        public event ValidaAgenteCompletedEventHandler ValidaAgenteCompleted;
        
        /// <remarks/>
        public event ValidaAllECompletedEventHandler ValidaAllECompleted;
        
        /// <remarks/>
        public event ValidaAgenteECompletedEventHandler ValidaAgenteECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://validar/", ResponseNamespace="http://validar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultadoValidacion ValidaAll([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("ValidaAll", new object[] {
                        xml});
            return ((resultadoValidacion)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaAllAsync(string xml) {
            this.ValidaAllAsync(xml, null);
        }
        
        /// <remarks/>
        public void ValidaAllAsync(string xml, object userState) {
            if ((this.ValidaAllOperationCompleted == null)) {
                this.ValidaAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaAllOperationCompleted);
            }
            this.InvokeAsync("ValidaAll", new object[] {
                        xml}, this.ValidaAllOperationCompleted, userState);
        }
        
        private void OnValidaAllOperationCompleted(object arg) {
            if ((this.ValidaAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaAllCompleted(this, new ValidaAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://validar/", ResponseNamespace="http://validar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultadoValidacion ValidaAgente([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string agente) {
            object[] results = this.Invoke("ValidaAgente", new object[] {
                        xml,
                        agente});
            return ((resultadoValidacion)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaAgenteAsync(string xml, string agente) {
            this.ValidaAgenteAsync(xml, agente, null);
        }
        
        /// <remarks/>
        public void ValidaAgenteAsync(string xml, string agente, object userState) {
            if ((this.ValidaAgenteOperationCompleted == null)) {
                this.ValidaAgenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaAgenteOperationCompleted);
            }
            this.InvokeAsync("ValidaAgente", new object[] {
                        xml,
                        agente}, this.ValidaAgenteOperationCompleted, userState);
        }
        
        private void OnValidaAgenteOperationCompleted(object arg) {
            if ((this.ValidaAgenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaAgenteCompleted(this, new ValidaAgenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://validar/", ResponseNamespace="http://validar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultadoValidacion ValidaAllE([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Parametro) {
            object[] results = this.Invoke("ValidaAllE", new object[] {
                        xml,
                        Parametro});
            return ((resultadoValidacion)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaAllEAsync(string xml, string Parametro) {
            this.ValidaAllEAsync(xml, Parametro, null);
        }
        
        /// <remarks/>
        public void ValidaAllEAsync(string xml, string Parametro, object userState) {
            if ((this.ValidaAllEOperationCompleted == null)) {
                this.ValidaAllEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaAllEOperationCompleted);
            }
            this.InvokeAsync("ValidaAllE", new object[] {
                        xml,
                        Parametro}, this.ValidaAllEOperationCompleted, userState);
        }
        
        private void OnValidaAllEOperationCompleted(object arg) {
            if ((this.ValidaAllECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaAllECompleted(this, new ValidaAllECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://validar/", ResponseNamespace="http://validar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultadoValidacion ValidaAgenteE([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string agente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Parametro) {
            object[] results = this.Invoke("ValidaAgenteE", new object[] {
                        xml,
                        agente,
                        Parametro});
            return ((resultadoValidacion)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaAgenteEAsync(string xml, string agente, string Parametro) {
            this.ValidaAgenteEAsync(xml, agente, Parametro, null);
        }
        
        /// <remarks/>
        public void ValidaAgenteEAsync(string xml, string agente, string Parametro, object userState) {
            if ((this.ValidaAgenteEOperationCompleted == null)) {
                this.ValidaAgenteEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaAgenteEOperationCompleted);
            }
            this.InvokeAsync("ValidaAgenteE", new object[] {
                        xml,
                        agente,
                        Parametro}, this.ValidaAgenteEOperationCompleted, userState);
        }
        
        private void OnValidaAgenteEOperationCompleted(object arg) {
            if ((this.ValidaAgenteECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaAgenteECompleted(this, new ValidaAgenteECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validar/")]
    public partial class resultadoValidacion {
        
        private string codigoField;
        
        private string efosField;
        
        private string estatusField;
        
        private string mensajeField;
        
        private string npacField;
        
        private string observacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string efos {
            get {
                return this.efosField;
            }
            set {
                this.efosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string npac {
            get {
                return this.npacField;
            }
            set {
                this.npacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ValidaAllCompletedEventHandler(object sender, ValidaAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultadoValidacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultadoValidacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ValidaAgenteCompletedEventHandler(object sender, ValidaAgenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaAgenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaAgenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultadoValidacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultadoValidacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ValidaAllECompletedEventHandler(object sender, ValidaAllECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaAllECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaAllECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultadoValidacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultadoValidacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ValidaAgenteECompletedEventHandler(object sender, ValidaAgenteECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaAgenteECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaAgenteECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultadoValidacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultadoValidacion)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591